In [1]:
import numpy as np

### Vector Operations

In [3]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [4]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

### Multiplication
- Vector-vector multiplication
- Matrix-vector multiplication
- Matrix-matrix multiplication

In [7]:
def vector_vector_mul(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [8]:
vector_vector_mul(u, v)

np.float64(14.0)

In [11]:
dot_product = np.dot(u, v) # Built in dot product function
dot_product

np.int64(14)

In [12]:
u.dot(v) # Multiplying two vectors

np.int64(14)

In [15]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [16]:
def matrix_vector_mul(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_mul(U[i], v)

    return result

In [17]:
matrix_vector_mul(U, v)

array([14.,  5.,  5.])

In [18]:
U.dot(v) # Built-in function

array([14,  5,  5])

In [19]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [20]:
U.dot(V) # In-Built function

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [23]:
def matrix_matrix_multi(U,V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_mul(U, vi)
        result[:, i] = Uvi

    return result

In [24]:
matrix_matrix_multi(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity matrix

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
I = np.eye(3)

In [27]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [28]:
V.dot(I) #Any matrix multiplied by an identity matrixs will always return the same matrix

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Inverse

In [31]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [33]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [34]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])