In [2]:
import numpy as np
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

# Creating one dimensional arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [8]:
a[2]

np.int64(3)

In [10]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimensional arrays

In [16]:
np.zeros((5, 2)) # five rows, two columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]) # rows are numbered top to bottom 0 -1 and columns are numbered left to right 0 -1
n

In [ ]:
n[0, 2]

In [19]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [20]:
# To access rows, pass in only the first arg
n[0]

array([ 1, 20,  3])

In [21]:
n[2] = [1, 1, 1] 
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [22]:
# To access column
n[:, 1]

array([20,  5,  1])

In [24]:
n[:, 2] = [0, 1, 2]
n

array([[1, 0, 0],
       [4, 1, 1],
       [1, 2, 2]])

In [25]:
n[:, 1] = [20, 5, 1]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

Randomly generated arrays

In [27]:
np.random.seed(2) # This is to fix the random numbers from changing
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [28]:
np.random.seed(2) 
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [29]:
np.random.seed(2) 
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [30]:
np.random.seed(2) 
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [42]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [43]:
a + 1

array([1, 2, 3, 4, 5])

In [44]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [45]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

# Comparison operations

In [46]:
a

array([0, 1, 2, 3, 4])

In [47]:
a >= 2

array([False, False,  True,  True,  True])

In [48]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [49]:
a > b

array([False, False,  True,  True,  True])

In [50]:
a[a > b] # returns the arrary for a for which the condition in the brackets are true

array([2, 3, 4])

# Summarizing operations

In [51]:
a

array([0, 1, 2, 3, 4])

In [52]:
a.min()

np.int64(0)

In [53]:
a.max()

np.int64(4)

In [54]:
a.sum()

np.int64(10)

In [55]:
a.mean()

np.float64(2.0)

In [57]:
np.median(a)

np.float64(2.0)

In [59]:
a.std()

np.float64(1.4142135623730951)

In [61]:
n.sum() # also works for n-dimensional array

np.int64(35)